export const LANDING = '/'
export const HOME = '/home'
export const SIGN_UP = '/signup'
export const SIGN_IN = '/signin'
export const PASSWORD_FORGET = '/pw-forget'
export const ACCOUNT = '/account'
export const HOME_CONTAINER = '/home_container'
export const ADMIN = '/admin'